Fix exception during loading on the beta branch: 0.2.5898.25997
Method AddPrefab was removed from the world manager. The change is compatible with 0.2.5898.25997

MissingMethodException: Method not found: void .WorldManager.AddPrefab(Assets.Scripts.Objects.Thing)